# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190305_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='certified_comment',
            field=models.BooleanField(default=False),
        ),
    ]
